export const testMeals = [
	{
		'idMeal': '52768',
		'strMeal': 'Apple Frangipan Tart',
		'strDrinkAlternate': null,
		'strCategory': 'Dessert',
		'strArea': 'British',
		'strInstructions': 'Preheat the oven to 200C/180C Fan/Gas 6.\r\nPut the biscuits in a large re-sealable freezer bag and bash with a rolling pin into fine crumbs. Melt the butter in a small pan, then add the biscuit crumbs and stir until coated with butter. Tip into the tart tin and, using the back of a spoon, press over the base and sides of the tin to give an even layer. Chill in the fridge while you make the filling.\r\nCream together the butter and sugar until light and fluffy. You can do this in a food processor if you have one. Process for 2-3 minutes. Mix in the eggs, then add the ground almonds and almond extract and blend until well combined.\r\nPeel the apples, and cut thin slices of apple. Do this at the last minute to prevent the apple going brown. Arrange the slices over the biscuit base. Spread the frangipane filling evenly on top. Level the surface and sprinkle with the flaked almonds.\r\nBake for 20-25 minutes until golden-brown and set.\r\nRemove from the oven and leave to cool for 15 minutes. Remove the sides of the tin. An easy way to do this is to stand the tin on a can of beans and push down gently on the edges of the tin.\r\nTransfer the tart, with the tin base attached, to a serving plate. Serve warm with cream, crème fraiche or ice cream.',
		'strMealThumb': 'https://www.themealdb.com/images/media/meals/wxywrq1468235067.jpg',
		'strTags': 'Tart,Baking,Fruity',
		'strYoutube': 'https://www.youtube.com/watch?v=rp8Slv4INLk',
		'strIngredient1': 'digestive biscuits',
		'strIngredient2': 'butter',
		'strIngredient3': 'Bramley apples',
		'strIngredient4': 'butter, softened',
		'strIngredient5': 'caster sugar',
		'strIngredient6': 'free-range eggs, beaten',
		'strIngredient7': 'ground almonds',
		'strIngredient8': 'almond extract',
		'strIngredient9': 'flaked almonds',
		'strIngredient10': '',
		'strIngredient11': '',
		'strIngredient12': '',
		'strIngredient13': '',
		'strIngredient14': '',
		'strIngredient15': '',
		'strIngredient16': null,
		'strIngredient17': null,
		'strIngredient18': null,
		'strIngredient19': null,
		'strIngredient20': null,
		'strMeasure1': '175g/6oz',
		'strMeasure2': '75g/3oz',
		'strMeasure3': '200g/7oz',
		'strMeasure4': '75g/3oz',
		'strMeasure5': '75g/3oz',
		'strMeasure6': '2',
		'strMeasure7': '75g/3oz',
		'strMeasure8': '1 tsp',
		'strMeasure9': '50g/1¾oz',
		'strMeasure10': '',
		'strMeasure11': '',
		'strMeasure12': '',
		'strMeasure13': '',
		'strMeasure14': '',
		'strMeasure15': '',
		'strMeasure16': null,
		'strMeasure17': null,
		'strMeasure18': null,
		'strMeasure19': null,
		'strMeasure20': null,
		'strSource': null,
		'strImageSource': null,
		'strCreativeCommonsConfirmed': null,
		'dateModified': null
	},
	{
		'idMeal': '52824',
		'strMeal': 'Beef Sunday Roast',
		'strDrinkAlternate': null,
		'strCategory': 'Beef',
		'strArea': 'British',
		'strInstructions': 'Cook the Broccoli and Carrots in a pan of boiling water until tender.\r\n\r\nRoast the Beef and Potatoes in the oven for 45mins, the potatoes may need to be checked regularly to not overcook.\r\n\r\nTo make the Yorkshire puddings:\r\nHeat oven to 230C/fan 210C/gas 8. Drizzle a little sunflower oil evenly into 2 x 4-hole Yorkshire pudding tins or a 12-hole non-stick muffin tin and place in the oven to heat through\r\nTo make the batter, tip 140g plain flour into a bowl and beat in four eggs until smooth. Gradually add 200ml milk and carry on beating until the mix is completely lump-free. Season with salt and pepper. Pour the batter into a jug, then remove the hot tins from the oven. Carefully and evenly pour the batter into the holes. Place the tins back in the oven and leave undisturbed for 20-25 mins until the puddings have puffed up and browned. Serve immediately.\r\n\r\nPlate up and add the Gravy as desired.',
		'strMealThumb': 'https://www.themealdb.com/images/media/meals/ssrrrs1503664277.jpg',
		'strTags': 'MainMeal',
		'strYoutube': 'https://www.youtube.com/watch?v=2l3-dBdNehY',
		'strIngredient1': 'Beef',
		'strIngredient2': 'Broccoli',
		'strIngredient3': 'Potatoes',
		'strIngredient4': 'Carrots',
		'strIngredient5': 'plain flour',
		'strIngredient6': 'Eggs',
		'strIngredient7': 'milk',
		'strIngredient8': 'sunflower oil',
		'strIngredient9': null,
		'strIngredient10': null,
		'strIngredient11': null,
		'strIngredient12': null,
		'strIngredient13': null,
		'strIngredient14': null,
		'strIngredient15': null,
		'strIngredient16': null,
		'strIngredient17': null,
		'strIngredient18': null,
		'strIngredient19': null,
		'strIngredient20': null,
		'strMeasure1': '8 slices',
		'strMeasure2': '12 florets',
		'strMeasure3': '1 Packet',
		'strMeasure4': '1 Packet',
		'strMeasure5': '140g',
		'strMeasure6': '4',
		'strMeasure7': '200ml',
		'strMeasure8': 'drizzle (for cooking)',
		'strMeasure9': '',
		'strMeasure10': '',
		'strMeasure11': '',
		'strMeasure12': '',
		'strMeasure13': '',
		'strMeasure14': '',
		'strMeasure15': '',
		'strMeasure16': '',
		'strMeasure17': '',
		'strMeasure18': '',
		'strMeasure19': '',
		'strMeasure20': '',
		'strSource': 'https://www.bbcgoodfood.com/recipes/9020/best-yorkshire-puddings',
		'strImageSource': null,
		'strCreativeCommonsConfirmed': null,
		'dateModified': null
	},
	{
		'idMeal': '52823',
		'strMeal': 'Salmon Prawn Risotto',
		'strDrinkAlternate': null,
		'strCategory': 'Seafood',
		'strArea': 'Italian',
		'strInstructions': 'Melt the butter in a thick-based pan and gently cook the onion without colour until it is soft.\r\nAdd the rice and stir to coat all the grains in the butter\r\nAdd the wine and cook gently stirring until it is absorbed\r\nGradually add the hot stock, stirring until each addition is absorbed. Keep stirring until the rice is tender\r\nSeason with the lemon juice and zest, and pepper to taste. (there will probably be sufficient saltiness from the salmon to not need to add salt) Stir gently to heat through\r\nServe scattered with the Parmesan and seasonal vegetables.\r\nGrill the salmon and gently place onto the risotto with the prawns and asparagus',
		'strMealThumb': 'https://www.themealdb.com/images/media/meals/xxrxux1503070723.jpg',
		'strTags': 'Fish',
		'strYoutube': 'https://www.youtube.com/watch?v=V2PMvBv52IE',
		'strIngredient1': 'butter',
		'strIngredient2': 'onion',
		'strIngredient3': 'rice',
		'strIngredient4': 'white wine',
		'strIngredient5': 'vegetable stock',
		'strIngredient6': 'lemon',
		'strIngredient7': 'King Prawns',
		'strIngredient8': 'salmon',
		'strIngredient9': 'asparagus',
		'strIngredient10': 'black pepper',
		'strIngredient11': 'Parmesan',
		'strIngredient12': '',
		'strIngredient13': '',
		'strIngredient14': '',
		'strIngredient15': '',
		'strIngredient16': '',
		'strIngredient17': '',
		'strIngredient18': '',
		'strIngredient19': '',
		'strIngredient20': '',
		'strMeasure1': '50g/2oz',
		'strMeasure2': '1 finely chopped ',
		'strMeasure3': '150g',
		'strMeasure4': '125ml ',
		'strMeasure5': '1 litre hot',
		'strMeasure6': 'The juice and zest of one',
		'strMeasure7': '240g large',
		'strMeasure8': '150g',
		'strMeasure9': '100g tips blanched briefly in boiling water',
		'strMeasure10': 'ground',
		'strMeasure11': '50g shavings',
		'strMeasure12': '',
		'strMeasure13': '',
		'strMeasure14': '',
		'strMeasure15': '',
		'strMeasure16': '',
		'strMeasure17': '',
		'strMeasure18': '',
		'strMeasure19': '',
		'strMeasure20': '',
		'strSource': 'http://www.rangemaster.co.uk/rangemaster-owners/recipes-ideas-inspiration/recipes/mains/prawn-and-hot-smoked-salmon-risotto-with-asparagus',
		'strImageSource': null,
		'strCreativeCommonsConfirmed': null,
		'dateModified': null
	},
	{
		'idMeal': '52849',
		'strMeal': 'Spinach & Ricotta Cannelloni',
		'strDrinkAlternate': null,
		'strCategory': 'Vegetarian',
		'strArea': 'Italian',
		'strInstructions': 'First make the tomato sauce. Heat the oil in a large pan and fry the garlic for 1 min. Add the sugar, vinegar, tomatoes and some seasoning and simmer for 20 mins, stirring occasionally, until thick. Add the basil and divide the sauce between 2 or more shallow ovenproof dishes (see Tips for freezing, below). Set aside. Make a sauce by beating the mascarpone with the milk until smooth, season, then set aside.\r\n\r\nPut the spinach in a large colander and pour over a kettle of boiling water to wilt it (you may need to do this in batches). When cool enough to handle squeeze out the excess water. Roughly chop the spinach and mix in a large bowl with 100g Parmesan and ricotta. Season well with salt, pepper and the nutmeg.\r\n\r\nHeat oven to 200C/180C fan/gas 6. Using a piping bag or plastic food bag with the corner snipped off, squeeze the filling into the cannelloni tubes. Lay the tubes, side by side, on top of the tomato sauce and spoon over the mascarpone sauce. Top with Parmesan and mozzarella. You can now freeze the cannelloni, uncooked, or you can cook it first and then freeze. Bake for 30-35 mins until golden and bubbling. Remove from oven and let stand for 5 mins before serving.',
		'strMealThumb': 'https://www.themealdb.com/images/media/meals/wspuvp1511303478.jpg',
		'strTags': null,
		'strYoutube': 'https://www.youtube.com/watch?v=rYGaEJjyLQA',
		'strIngredient1': 'Olive Oil',
		'strIngredient2': 'Garlic',
		'strIngredient3': 'Caster Sugar',
		'strIngredient4': 'Red Wine Vinegar',
		'strIngredient5': 'Chopped Tomatoes',
		'strIngredient6': 'Basil Leaves',
		'strIngredient7': 'Mascarpone',
		'strIngredient8': 'Milk',
		'strIngredient9': 'Parmesan',
		'strIngredient10': 'Mozzarella',
		'strIngredient11': 'Spinach',
		'strIngredient12': 'Parmesan',
		'strIngredient13': 'Ricotta',
		'strIngredient14': 'Nutmeg',
		'strIngredient15': 'Cannellini Beans',
		'strIngredient16': '',
		'strIngredient17': '',
		'strIngredient18': '',
		'strIngredient19': '',
		'strIngredient20': '',
		'strMeasure1': '3 tbsp',
		'strMeasure2': '8 cloves chopped',
		'strMeasure3': '3 tbsp',
		'strMeasure4': '2 tblsp ',
		'strMeasure5': '3 400g Cans',
		'strMeasure6': 'Bunch',
		'strMeasure7': '2 tubs',
		'strMeasure8': '3 tbsp',
		'strMeasure9': '85g',
		'strMeasure10': '2 sliced',
		'strMeasure11': '1kg',
		'strMeasure12': '100g ',
		'strMeasure13': '3 tubs',
		'strMeasure14': 'pinch',
		'strMeasure15': '400g',
		'strMeasure16': '',
		'strMeasure17': '',
		'strMeasure18': '',
		'strMeasure19': '',
		'strMeasure20': '',
		'strSource': 'https://www.bbcgoodfood.com/recipes/531632/spinach-and-ricotta-cannelloni',
		'strImageSource': null,
		'strCreativeCommonsConfirmed': null,
		'dateModified': null
	}
];