name: Periodic checks

on:
  schedule:
    - cron: '1 1 * * *'

jobs:
  periodic_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2
        with:
          url: https://retsipi.web.app/api/health
