name: Deployment pipeline

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  build_test_and_deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
          COMMIT_MESSAGES_STRING: join(env.COMMIT_MESSAGES)
        run: echo "$COMMIT_MESSAGES"
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          run: | 
            npx cypress cache path
            npm run test
          start: npm run start
          wait-on: http://localhost:3003
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        if: ${{ contains(env.COMMIT_MESSAGES_STRING, '\#skip') == false }}
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          DEFAULT_BUMP: patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}